dataset_class: Spambase
data_dir: ./datasets

random_seeds: [2, 25, 42, 52, 99, 103, 250, 666, 777, 2026]
# c from 0 to 1 inclusive with step 0.1
c_values: [0.05, 0.5]
scenarios: [case-control]
selection_strategies: ["sar_pusb", "sar_lbeA", "sar_lbeB"]

val_ratio: 0.01
target_prevalence: null
with_replacement: true
also_print_dataset_stats: false

label_scheme:
  true_positive_label: 1
  true_negative_label: 0
  pu_labeled_label: 1
  pu_unlabeled_label: -1
