robustpu:
  batch_size: 256
  seed: 42
  optimizer: "adam"
  label_scheme:
    true_positive_label: 1
    true_negative_label: 0
    pu_labeled_label: 1
    pu_unlabeled_label: -1
  checkpoint:
    enabled: true
    save_model: false
    monitor: "val_f1"
    mode: "max"
    early_stopping:
      enabled: true
      patience: 20
      min_delta: 0.0001

  pre_train:
    epochs: 20
    lr: 0.0001
    weight_decay: 0.0001
    batch_size: 256
    loss: "nnpu"

  main_train:
    epochs: 5
    inner_epochs: 5
    lr: 0.01
    weight_decay: 0.0
    batch_size: 256
    loss: "bce"
    hardness: "logistic"
    spl_type: "linear"
    scheduler_p:
      type: "linear"
      alpha: 0.1
      max_thresh: 1.0
      grow_steps: 10
      temper: 1.0
    scheduler_n:
      type: "linear"
      alpha: 0.11
      max_thresh: 1.0
      grow_steps: 10
      temper: 1.5
    moving_ratio: 0.0
    restart: false
