dataset_class: Spambase
data_dir: ./datasets

random_seeds: [42]
# c from 0 to 1 inclusive with step 0.1
c_values: [0.1]
scenarios: [case-control]
selection_strategies: ["random"]

val_ratio: 0.01
target_prevalence: null
with_replacement: true
also_print_dataset_stats: false

label_scheme:
  true_positive_label: 1
  true_negative_label: 0
  pu_labeled_label: 1
  pu_unlabeled_label: -1
