dataset_class: IMDB
data_dir: ./datasets
random_seeds: [42]

# c from 0 to 1 inclusive with step 0.1
c_values: [0.1]
scenarios: [case-control]
selection_strategies: ["random"]

# Optional knobs
val_ratio: 0.01
target_prevalence: null
with_replacement: true
also_print_dataset_stats: false

# SBERT encoding settings
sbert_model_name: all-MiniLM-L6-v2
sbert_model_path: ./scripts/models/all-MiniLM-L6-v2
sbert_embeddings_path: ./scripts/embeddings/imdb_sbert_embeddings.npz
