dataset_class: FashionMNIST
data_dir: ./datasets
random_seeds: [2, 25, 42, 52, 99, 103, 250, 666, 777, 2026]

# c from 0 to 1 inclusive with step 0.1
c_values: [0.1]
scenarios: [case-control]
selection_strategies: ["random"]

# Optional knobs
val_ratio: 0.01
target_prevalence: null
with_replacement: true
also_print_dataset_stats: false

# Multi-class to binary mapping
label_scheme:
  positive_classes: [0, 2, 3, 4, 6]
  negative_classes: [1, 5, 7, 8, 9]
