dataset_class: AlzheimerMRI
data_dir: ./datasets/Alzheimer_MRI_4_classes_dataset
random_seeds: [42]

# c from 0 to 1 inclusive with step 0.1
c_values: [0.1]
scenarios: [case-control]
selection_strategies: ["random"]

# Optional knobs
val_ratio: 0.01
target_prevalence: null
with_replacement: true
# Control whether dataset statistics are also printed to stdout
also_print_dataset_stats: false

# Multi-class to binary mapping
label_scheme:
  positive_classes: ["NonDemented"]
  negative_classes: ["VeryMildDemented", "ModerateDemented", "MildDemented"]

# Image preprocessing parameters
image_size: [128, 128]
